# Generated by Django 4.1.7 on 2024-06-27 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharged', models.BooleanField(default=False)),
                ('admitted_date', models.DateField()),
                ('discharged_date', models.DateField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.patients')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('update_date', models.DateField()),
                ('medicine', models.TextField()),
                ('conclusion', models.TextField()),
                ('admission_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.discharge')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patients')),
            ],
        ),
    ]
